apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-06-22T04:38:49Z"
  generation: 1
  labels:
    app: wso2mi-deployment
  name: wso2mi-deployment
  namespace: default
  resourceVersion: "577317"
  uid: 37443871-6aae-4c67-b541-0e1d32ae710e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wso2mi-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wso2mi-deployment
    spec:
      containers:
      - image: wso2.demo/wso2mi:v4.2.0
        imagePullPolicy: IfNotPresent
        name: wso2mi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-06-22T04:38:49Z"
    lastUpdateTime: "2024-06-22T04:38:49Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-06-22T04:38:49Z"
    lastUpdateTime: "2024-06-22T04:38:49Z"
    message: ReplicaSet "wso2mi-deployment-7f6555d9d7" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
