apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-06-22T06:10:41Z"
  generation: 1
  labels:
    app: wso2iam-deployment
  name: wso2iam-deployment
  namespace: default
  resourceVersion: "578126"
  uid: 579779b0-8833-41ce-ba35-9348f6e7723c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wso2iam-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wso2iam-deployment
    spec:
      containers:
      - image: wso2.demo/wso2iam:v7.0.0
        imagePullPolicy: IfNotPresent
        name: wso2iam
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-06-22T06:10:41Z"
    lastUpdateTime: "2024-06-22T06:10:41Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-06-22T06:10:41Z"
    lastUpdateTime: "2024-06-22T06:10:41Z"
    message: ReplicaSet "wso2iam-deployment-55776846b7" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
