apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wso2iam-deployment
  name: wso2iam-service
spec:
  ports:
  - port: 9444
    protocol: TCP
    nodePort: 30003
    targetPort: 9444
  selector:
    app: wso2iam-deployment
  type: NodePort
status:
  loadBalancer: {}
