apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-06-22T04:30:30Z"
  generation: 1
  labels:
    app: paymentsvc
  name: paymentsvc
  namespace: default
  resourceVersion: "577143"
  uid: ba3529f3-f15d-4c57-95a9-71f7ed800226
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: paymentsvc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: paymentsvc
    spec:
      containers:
      - image: wso2.demo/paymentsvc:v1
        imagePullPolicy: IfNotPresent
        name: paymentsvc
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-06-22T04:30:30Z"
    lastUpdateTime: "2024-06-22T04:30:30Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-06-22T04:30:30Z"
    lastUpdateTime: "2024-06-22T04:30:30Z"
    message: ReplicaSet "paymentsvc-664d8f685c" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
