apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: paymentsvc
  name: paymentsvc
spec:
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30001
    targetPort: 8080
  selector:
    app: paymentsvc
  type: NodePort
status:
  loadBalancer: {}
