apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-06-22T11:45:47Z"
  generation: 1
  labels:
    app: payment-ui-deployment
  name: payment-ui-deployment
  namespace: default
  resourceVersion: "582501"
  uid: fff3355b-92f3-4359-99fb-61c2ad7f732c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: payment-ui-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment-ui-deployment
    spec:
      containers:
      - image: wso2.demo/ui:v1.0.0
        imagePullPolicy: IfNotPresent
        name: ui
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-06-22T11:45:47Z"
    lastUpdateTime: "2024-06-22T11:45:47Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-06-22T11:45:47Z"
    lastUpdateTime: "2024-06-22T11:45:47Z"
    message: ReplicaSet "payment-ui-deployment-577698bf4d" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
