apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-06-22T11:42:11Z"
  generation: 1
  labels:
    app: wso2am-deployment
  name: wso2am-deployment
  namespace: default
  resourceVersion: "582401"
  uid: 764e1992-d7fa-4d97-b53e-ff8b49b51f6d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wso2am-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wso2am-deployment
    spec:
      containers:
      - image: wso2.demo/wso2apim:v4.3.0
        imagePullPolicy: IfNotPresent
        name: wso2apim
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-06-22T11:42:11Z"
    lastUpdateTime: "2024-06-22T11:42:11Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-06-22T11:42:11Z"
    lastUpdateTime: "2024-06-22T11:42:11Z"
    message: ReplicaSet "wso2am-deployment-b77f48596" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
