apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wso2am-deployment
  name: wso2am-service
spec:
  ports:
  - port: 9445
    protocol: TCP
    nodePort: 30004
    targetPort: 9445
    name: management
  - port: 8245
    protocol: TCP
    nodePort: 30005
    targetPort: 8245
    name: gateway
  selector:
    app: wso2am-deployment
  type: NodePort
status:
  loadBalancer: {}
